const scripts = [
    "asciidoc",
    "bc",
    "bf",
    "c",
    "csharp",
    "c++",
    "chapel",
    "CHICKEN",
    "clojure",
    "clojure-macros",
    "COBOL",
    "coffeescript",
    "coldfusion",
    "Common-Lisp",
    "Coq",
    "crystal",
    "css",
    "cypher",
    "D",
    "dart",
    "Dhall",
    "docker",
    "edn",
    "elisp",
    "elixir",
    "Elm",
    "erlang",
    "Fsharp",
    "factor",
    "forth",
    "Fortran",
    "Go",
    "Groovy",
    "Hack",
    "haml",
    "Haskell",
    "haxe",
    "HQ9+",
    "html",
    "hy",
    "Inform7",
    "Janet",
    "java",
    "javascript",
    "json",
    "jsonnet",
    "Julia",
    "kdb+",
    "kotlin",
    "latex",
    "LBStanza",
    "LDPL",
    "less",
    "LFE",
    "LiveScript",
    "Logtalk",
    "LOLCODE",
    "Lua",
    "M",
    "markdown",
    "Matlab",
    "mercury",
    "MIPS",
    "montilang",
    "moonscript",
    "neat",
    "Nim",
    "nix",
    "ObjectiveC",
    "OCaml",
    "Paren",
    "Pascal",
    "PCRE",
    "perl",
    "PHP",
    "Pod",
    "pogoscript",
    "processing",
    "prolog",
    "protocolbuffers",
    "Pug",
    "purescript",
    "Python",
    "Pythonlegacy",
    "Qsharp",
    "R",
    "racket",
    "Raku",
    "reason",
    "Red",
    "RST",
    "ruby",
    "Rust",
    "sass",
    "Scala",
    "self",
    "SmallBASIC",
    "Smalltalk",
    "Solidity",
    "SQL",
    "Standard-ML",
    "stylus",
    "swift",
    "Tcl",
    "textile",
    "toml",
    "TypeScript",
    "vala",
    "Vimscript",
    "VisualBasic",
    "Vyper",
    "WebAssembly",
    "whip",
    "wolfram",
    "xml",
    "yaml",
    "amd",
    "AngularJS",
    "ansible",
    "awk",
    "bash",
    "cmake",
    "compojure",
    "composer",
    "DirectX9",
    "emacs",
    "git",
    "jquery",
    "linker",
    "make",
    "Mercurial",
    "messagepack",
    "OpenCV",
    "OpenGL",
    "p5",
    "powershell",
    "PyQT",
    "Qt",
    "raylib",
    "ruby-ecosystem",
    "ShutIt",
    "Pythonstatcomp",
    "tcsh",
    "tmux",
    "vim",
    "zfs"
].map(s => `\`${s}\``.toLowerCase())


module.exports = {
    name: 'syntax',
    description: 'Get an image and title from a random r/programmerhumor post',
    execute(msg, args) {
        let arg = args.length != 0 ? args[0].toLowerCase().replace(/\b#/, 'sharp') : '';
        if (scripts.includes(`\`${arg}\``)) {
            arg = arg == 'lolcode' ? 'LOLCODE' : 'lolcode';
            msg.channel.send(`https://learnxinyminutes.com/docs/${arg.replace(/`/g, "")}/`)
        } else if (args == 'options') {
            msg.channel.send({
                "embed":
                {
                    "title": "__Syntax Options__",
                    "description": `${scripts.toString().replace(/,/g, ' ')}`,
                    "url": "https://learnxinyminutes.com",
                    "color": null
                }
            });

        } else {
            msg.channel.send('Uh Oh! that is either not a valid language or isn\'t supported by this database. for all the valid languages please do \"!syntax options\"')
        }
    }
}